### ISSUE TITLE
Test su modulo Pandas

### ISSUE THREAD

**Issue by andreava78-2020** [itpassdev/LEAMACHINE#4]
Di seguito sono riportati i metodi (senza usare salvo rari casi parametri particolari) che sono stati testati sull'installazione. Sono stati testati anche il funzionamento su test condizionali e inserimento / cancellazione di colonne e il risultato è confortante.

Da approfondire il metodo _to_excel_ che va sin errore causa la mancanza del modulo _openpyxl_
La stessa situazione si è verificata sul mio MacOs in Anaconda ed è stata risolta con l'installazione del pacchetto mancante ma direttamente da comando conda install openpyxl

[Metodi_Pandas.docx](https://github.com/itpassdev/LEAMACHINE/files/4610716/Metodi_Pandas.docx)

**Comment by andreava78-2020** [comment]
Valutare eventuale installazione del modulo _openpyxl_ per far funzionare il metodo nativo di pandas _to_excel_
Verificato da terminale che il modulo è al momento mancante nel sistema e salvo errori non risulta fra quelli disponibili da IBM

**Comment by AndreaRibuoli** [comment]
Grazie Andrea. Lo ho installato tramite **pip3**.
Fammi sapere se risponde alle tue specifiche...

```
   $                                                                                                                                
 > pip3 install openpyxl                                                                                                            
   Collecting openpyxl                                                                                                              
     Downloading openpyxl-3.0.3.tar.gz (172 kB)                                                                                     
    [K     |################################| 172 kB 1.6 MB/s eta 0:00:01                                                           
    [?25hCollecting jdcal                                                                                                           
     Downloading jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)                                                                          
   Collecting et_xmlfile                                                                                                            
     Downloading et_xmlfile-1.0.1.tar.gz (8.4 kB)                                                                                   
   Building wheels for collected packages: openpyxl, et-xmlfile                                                                     
     Building wheel for openpyxl (setup.py) ...  [?25ldone                                                                          
    [?25h  Created wheel for openpyxl: filename=openpyxl-3.0.3-py2.py3-none-any.whl size=241262 sha256=f70641641bb76937f00cf9aae4bff819b32b2c6a1d87620b5e3971264e443a3e                                                                                              
     Stored in directory: /home/AndreaRibuoli/.cache/pip/wheels/a2/97/2a/d5e43384faa87a34b198b8d75e03e7130e70321ea446f98703         
     Building wheel for et-xmlfile (setup.py) ...  [?25ldone                                                                        
    [?25h  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8915 sha256=735a3912973962b0efc68de79f452445c986203c5b65890984c20fade4f0a8ca                                                                                                
     Stored in directory: /home/AndreaRibuoli/.cache/pip/wheels/ef/92/e0/956c00decf3091294b8800d9104f6169a1adacfaafd122ed42         
   Successfully built openpyxl et-xmlfile                                                                                           
   Installing collected packages: jdcal, et-xmlfile, openpyxl                                                                       
   Successfully installed et-xmlfile-1.0.1 jdcal-1.4.1 openpyxl-3.0.3                                                               
```

**Comment by andreava78-2020** [comment]
> Grazie Andrea. Lo ho installato tramite **pip3**.
> Fammi sapere se risponde alle tue specifiche...
> 
> ```
>    $                                                                                                                                
>  > pip3 install openpyxl                                                                                                            
>    Collecting openpyxl                                                                                                              
>      Downloading openpyxl-3.0.3.tar.gz (172 kB)                                                                                     
>     [K     |################################| 172 kB 1.6 MB/s eta 0:00:01                                                           
>     [?25hCollecting jdcal                                                                                                           
>      Downloading jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)                                                                          
>    Collecting et_xmlfile                                                                                                            
>      Downloading et_xmlfile-1.0.1.tar.gz (8.4 kB)                                                                                   
>    Building wheels for collected packages: openpyxl, et-xmlfile                                                                     
>      Building wheel for openpyxl (setup.py) ...  [?25ldone                                                                          
>     [?25h  Created wheel for openpyxl: filename=openpyxl-3.0.3-py2.py3-none-any.whl size=241262 sha256=f70641641bb76937f00cf9aae4bff819b32b2c6a1d87620b5e3971264e443a3e                                                                                              
>      Stored in directory: /home/AndreaRibuoli/.cache/pip/wheels/a2/97/2a/d5e43384faa87a34b198b8d75e03e7130e70321ea446f98703         
>      Building wheel for et-xmlfile (setup.py) ...  [?25ldone                                                                        
>     [?25h  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8915 sha256=735a3912973962b0efc68de79f452445c986203c5b65890984c20fade4f0a8ca                                                                                                
>      Stored in directory: /home/AndreaRibuoli/.cache/pip/wheels/ef/92/e0/956c00decf3091294b8800d9104f6169a1adacfaafd122ed42         
>    Successfully built openpyxl et-xmlfile                                                                                           
>    Installing collected packages: jdcal, et-xmlfile, openpyxl                                                                       
>    Successfully installed et-xmlfile-1.0.1 jdcal-1.4.1 openpyxl-3.0.3                                                               
> ```

Grazie Andrea, testato e funzionante il funzionamento base, direi che è a posto
