### ISSUE TITLE
Utilizzo di read_sql direttamente da pandas

### ISSUE THREAD

**Issue by andreava78-2020** [itpassdev/LEAMACHINE#5]
Ho provato a utilizzare il metodo read_sql direttamente da pandas per leggere una tabella su IBM i ma non funziona penso per la mancanza della gestione del cursore nel pacchetto ibm_db
Vorrei provare a fare il wrap della connessione su ibm_dbi che probabilmente permetterebbe l'utilizzo corretto ma _ibm_dbi_ non è installato.
Se riuscissimo a farlo funzionare potremmo provare a utilizzare il metodo read_sql di pandas e provare a leggere direttamente dalla connessione di db2; ho fatto delle ricerche ed è una scelta che suggeriscono e vorrei provarla sul sistema.

L'errore di mancanza del pacchetto è il seguente:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-49-e7859d36ee59> in <module>
      1 import ibm_db
----> 2 import ibm_dbi
      3 conn_read = ibm_db.connect("*LOCAL","Utente","Password")
      4 
      5 conn = ibm_db_dbi.Connection(conn_read)

ModuleNotFoundError: No module named 'ibm_dbi'

**Comment by AndreaRibuoli** [comment]
Hai provato ad effettuare la connessione così:

<img width="717" alt="Schermata 2020-08-24 alle 21 34 07" src="https://user-images.githubusercontent.com/1822290/91088098-c3cdb800-e651-11ea-9cfd-a87629e2fbe7.png">

**Comment by andreava78-2020** [comment]
Cosi no, faccio una prova aprendo una connessione con questo modulo e
passandola a pandas e vediamo se va. L'obiettivo è renderlo trasparente a
pandas e sfruttare di conseguenza le funzionalità

Il Lun 24 Ago 2020, 21:36 AndreaRibuoli <notifications@github.com> ha
scritto:

**Comment by andreava78-2020** [comment]
Provato e funziona grazie!
Guardo un po' la documentazione, ha una sintassi curiosa...

![Schermata 2020-08-25 alle 19 17 34](https://user-images.githubusercontent.com/64212366/91206663-c8ed3e80-e707-11ea-8df9-7518dc3a439e.png)

**Comment by AndreaRibuoli** [comment]
Considero risolto il punto
